v5

diff --git a/ccbins b/ccbins
--- a/ccbins
+++ b/ccbins
@@ -49,29 +49,34 @@ print_pause() {
   sleep 2
 }
 
+reset_mod() {
+  local newloc=/data/adb/modules_update/$ID
+  rm -rf $newloc
+  mkdir -p /data/adb/modules_update/$ID/system/bin 2>/dev/null
+  cp -pf $MODDIR/system/bin/ccbins $newloc/system/bin/ccbins
+  cp -pf $MODDIR/* $newloc 2>/dev/null
+  touch $MODDIR/update
+  rm -f $newloc/update $newloc/tmp
+  echo -e "CCbins reset!\nReboot to apply it!\n"
+  sleep 2
+}
+
 check_updates() {
   echo -e "\nChecking for mod updates"
-  rm -f $MODDIR/tmp
+  rm -f $MODDIR/.updated
+  wget -qO $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/changelog.txt 2>/dev/null
   for i in mod-util.sh,MODUTILVCODE system/bin/ccbins,scriptver; do
     local file="$(echo $i | cut -d , -f1)" value="$(echo $i | cut -d , -f2)"
-    [ `wget -qO - https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/$(basename $file) 2>/dev/null | grep "^$value=" | cut -d = -f2` -gt `grep "^$value=" $MODDIR/$file | cut -d = -f2` ] && { echo -n 1 > $MODDIR/tmp; wget -qO $MODDIR/$file https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/$(basename $file) 2>/dev/null; }
+    if [ `wget -qO - https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/$(basename $file) 2>/dev/null | grep "^$value=" | cut -d = -f2` -gt `grep "^$value=" $MODDIR/$file | cut -d = -f2` ]; then
+      echo "$scriptver" > $MODDIR/.updated
+      wget -qO $MODDIR/$file https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/$(basename $file) 2>/dev/null
+      [ "$file" == "system/bin/ccbins" ] && { umount -l /$file; mount -o bind $MODDIR/$file /$file; }
+    fi
   done
 }
 
-check_bin_updates() {
-  echo -e "\nChecking for binary updates"
-  rm -f $MODDIR/tmp
-  [ -s $MODDIR/.installed ] || return 0
-  while read -r line; do
-    local bin="$(echo "$line" | awk '{print $1}')" insver="$(echo "$line" | awk '{print substr($2, 3, length($2) - 3)}')" binloc="$(echo "$line" | awk '{print $3}')"
-    curver="$(grep -w $bin $MODDIR/.binaries | awk '{print substr($2, 3, length($2) - 3)}')"
-    [ "$insver" == "/a" ] && insver="0.0"
-    [ $(echo "$curver $insver" | awk '{printf "%d", ($1 > $2)}') -eq 1 ] && echo "  $binloc: $bin ($insver -> $curver)" >> $MODDIR/tmp
-  done < $MODDIR/.installed
-}
-
 find_conflicts() {
-  echo -e "\nChecking for conflicting modules"
+  echo "Checking for conflicting modules"
   rm -f $MODDIR/tmp
   [ -s $MODDIR/.installed ] || return 0
   local locs="$(awk '{print $3}' $MODDIR/.installed | xargs -n1 | sort -u)" binaries="$(awk '{print $1}' $MODDIR/.installed | xargs -n1 | sort -u)"
@@ -140,7 +145,97 @@ change_loc() {
   done
 }
 
+check_conflicts() {
+  find $MOUNTPATH/*$insloc -mindepth 1 -maxdepth 1 -type f ! -path "$MOUNTPATH/\.*" ! -path "$MOUNTPATH/ccbins/*" \( -name $i \) 2>/dev/null | sed -r "s|$MOUNTPATH/(.*)/system/.*|\1|" > $MODDIR/tmp2
+  [ -s $MODDIR/tmp2 ] && echo -e "  Conflict ($insloc/$i) found in: $(cat $MODDIR/tmp2)!"
+  rm -f $MODDIR/tmp2
+}
+
 remove_binary() {
+  [ "$1" == "-f" ] && local force=true || force=false
+  for i in $(grep -w $binary $MODDIR/.binaries | awk '{print $3}' | sed "s/,/ /g"); do
+    $force || umount -l $insloc/$i
+    rm -f $MODDIR$insloc/$i
+    case $i in
+      "busybox"|"coreutils") 
+        for j in $MODDIR$insloc/*; do
+          if [ -L $j ]; then
+            $force || umount -l $insloc/$(basename $j)
+            rm -f $j
+          fi
+        done;;
+    esac
+  done
+  if [ "$extras" ] && ([ -z "$(grep -w $binary $MODDIR/.installed)" ] || $force); then
+    while read -r line; do
+      $force || umount -l /system/$line
+      rm -f $MODDIR/system/$line
+    done < $MODDIR/.$ibinary
+    rm -f $MODDIR/.$ibinary
+  fi
+}
+
+install_binary() {
+  [ "$1" == "-s" ] && local spin=true || spin=false
+  for i in $(grep -w $binary $MODDIR/.binaries | awk '{print $3}' | sed "s/,/ /g"); do
+    check_conflicts
+    $spin && { wget -O $MODDIR$insloc/$i https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i-$ARCH 2>/dev/null & e_spinner; } || wget -O $MODDIR$insloc/$i https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i-$ARCH 2>/dev/null
+    set_perm $MODDIR$insloc/$i 0 0 0755
+    case $i in
+      "busybox")
+        cd $MODDIR$insloc
+        for j in $($i --list); do
+          [ -e "/sbin/.magisk/mirror$insloc/$j" ] || [ -e "$j" ] || ln -sf $i $j
+        done
+        cd $dir
+        ;;
+      "coreutils")
+        cd $MODDIR$insloc
+        for j in $(./coreutils --help | sed -n "/^ \[/p"); do
+          if ([ ! -e "/sbin/.magisk/mirror$insloc/$j" ] && [ ! -e "$j" ] && [ "$j" != "[" ] && [ "$j" != "test" ]) || ([ "$j" == "cp" ] || [ "$j" == "mv" ]); then
+            ln -sf coreutils $j
+          fi
+        done
+        cd $dir;;
+    esac
+  done
+  if [ "$extras" ] && [ ! -f $MODDIR/.$ibinary ]; then
+    for i in $(echo $extras | sed "s|,| |g"); do
+      $spin && { wget -qO $MODDIR/$i.zip https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i.zip 2>/dev/null & e_spinner; } || wget -qO $MODDIR/$i.zip https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i.zip 2>/dev/null
+      unzip -l $MODDIR/$i.zip | awk '{print $4}' | sed -e '/^$/d' -e '/^Name$/d' -e '/^----$/d' -e '/\/$/d' >> $MODDIR/.$ibinary
+      unzip -qod $MODDIR/system $MODDIR/$i.zip
+      rm -f $MODDIR/$i.zip
+    done
+  fi
+}
+
+check_bin_updates() {
+  echo -e "\nChecking for binary updates"
+  rm -f $MODDIR/tmp
+  [ -s $MODDIR/.installed ] || return 0
+  while read -r line; do
+    local insloc="$(echo "$line" | awk '{print $3}')" binary="$(echo "$line" | awk '{print $1}')" insver="$(echo "$line" | awk '{print substr($2, 3, length($2) - 3)}')" binloc="$(echo "$line" | awk '{print $3}')"
+    local newver="$(grep -w $binary $MODDIR/.binaries | awk '{print substr($2, 3, length($2) - 3)}')" ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]') extras="$(grep -w $binary $MODDIR/.binaries | awk '{print $4}')"
+    [ "$insver" == "/a" ] && insver="0.0"
+    # Add 0 before final number if single digit or compare won't work
+    for i in insver newver; do
+      local beg=$(echo $(eval echo \$$i) | sed -r "s/(.*)\..*/\1./")
+      local end=$(echo $(eval echo \$$i) | sed "s/.*\.//")
+      [ $(echo $end | wc -m) -eq 2 ] && local end=0$end
+      local dec$i=$beg$end
+    done
+    [ $(echo "$decnewver $decinsver" | awk '{printf "%d", ($1 > $2)}') -eq 1 ] || continue
+    touch $MODDIR/tmp
+    echo " - Updating $binloc: $binary ($insver -> $newver)"
+    sed -i "\|$binary.*$binloc| s/$insver/$newver/" $MODDIR/.installed
+    remove_binary -f
+    install_binary
+    echo " - $binary has been updated!"
+  done < $MODDIR/.installed
+}
+
+remove_binary_menu() {
+  clear
   while true; do
     grep -w "$insloc" $MODDIR/.installed | awk '{print FNR + 1 ": " $1 " " $2}' > $MODDIR/tmp
     [ -s $MODDIR/tmp ] && sed -i "1i0: None, go back to main menu\n1: Remove all binaries listed below" $MODDIR/tmp || { print_pause "No binaries are installed to $insloc!\n"; break; }
@@ -165,40 +260,16 @@ remove_binary() {
       local ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]') extras="$(grep -w $binary $MODDIR/.binaries | awk '{print $4}')"
       sed -i "\|$binary.*$insloc|d" $MODDIR/.installed
       is_mounted $insloc/$ibinary && local unmount=true || local unmount=false
-      for i in $(grep -w $binary $MODDIR/.binaries | awk '{print $3}' | sed "s/,/ /g"); do
-        $unmount && umount -l $insloc/$i
-        rm -f $MODDIR$insloc/$i
-        case $i in
-          "busybox"|"coreutils") 
-            for j in $MODDIR$insloc/*; do
-              if [ -L $j ]; then
-                $unmount && umount -l $insloc/$(basename $j)
-                rm -f $j
-              fi
-            done;;
-        esac
-      done
-      if [ "$extras" ] && [ -z "$(grep -w $binary $MODDIR/.installed)" ]; then
-        while read -r line; do
-          $unmount && umount -l /system/$line
-          rm -f $MODDIR/system/$line
-        done < $MODDIR/.$ibinary
-        rm -f $MODDIR/.$ibinary
-      fi
+      remove_binary
       toybox find $MODDIR/system -type d -empty -delete >/dev/null 2>&1
       echo -e "$binary has been removed!\n"
     done
-    clear
   done
+  clear
 }
 
-check_conflicts() {
-  find $MOUNTPATH/*$insloc -mindepth 1 -maxdepth 1 -type f ! -path "$MOUNTPATH/\.*" ! -path "$MOUNTPATH/ccbins/*" \( -name $i \) 2>/dev/null | sed -r "s|$MOUNTPATH/(.*)/system/.*|\1|" > $MODDIR/tmp2
-  [ -s $MODDIR/tmp2 ] && echo -e "  Conflict ($insloc/$i) found in: $(cat $MODDIR/tmp2)!"
-  rm -f $MODDIR/tmp2
-}
-
-install_binary() {
+install_binary_menu() {
+  clear
   while true; do
     if [ -s $MODDIR/.installed ]; then
       local curbins="$(grep -w "$insloc" $MODDIR/.installed | awk '{print $1}' | sed -E 's/Busybox|Coreutils/Busybox Coreutils/')"
@@ -248,42 +319,12 @@ install_binary() {
       local ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]') extras="$(grep -w $binary $MODDIR/.binaries | awk '{print $4}')"
       echo "Downloading $binary"
       mkdir -p $MODDIR$insloc
-      for i in $(grep -w $binary $MODDIR/.binaries | awk '{print $3}' | sed "s/,/ /g"); do
-        check_conflicts
-        rm -f $MODDIR$insloc/$i 2>/dev/null
-        wget -O $MODDIR$insloc/$i https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i-$ARCH 2>/dev/null & e_spinner
-        set_perm $MODDIR$insloc/$i 0 0 0755
-        case $i in
-          "busybox")
-            cd $MODDIR$insloc
-            for j in $($i --list); do
-              [ -e "/sbin/.magisk/mirror$insloc/$j" ] || [ -e "$j" ] || ln -sf $i $j
-            done
-            cd $dir
-            ;;
-          "coreutils")
-            cd $MODDIR$insloc
-            for j in $(./coreutils --help | sed -n "/^ \[/p"); do
-              if ([ ! -e "/sbin/.magisk/mirror$insloc/$j" ] && [ ! -e "$j" ] && [ "$j" != "[" ] && [ "$j" != "test" ]) || ([ "$j" == "cp" ] || [ "$j" == "mv" ]); then
-                ln -sf coreutils $j
-              fi
-            done
-            cd $dir;;
-        esac
-      done
-      if [ "$extras" ] && [ ! -f $MODDIR/.$ibinary ]; then
-        for i in $(echo $extras | sed "s|,| |g"); do
-          wget -qO $MODDIR/$i.zip https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/$i.zip 2>/dev/null & e_spinner
-          unzip -l $MODDIR/$i.zip | awk '{print $4}' | sed -e '/^$/d' -e '/^Name$/d' -e '/^----$/d' -e '/\/$/d' >> $MODDIR/.$ibinary
-          unzip -qod $MODDIR/system $MODDIR/$i.zip
-          rm -f $MODDIR/$i.zip
-        done
-      fi
+      install_binary -s
       echo -e " - $binary has been installed!\n"
     done
-    clear
     echo -e "Reboot for changes to take effect\n"
   done
+  clear
 }
 
 backup_config() {
@@ -293,28 +334,92 @@ backup_config() {
   cp -af $MODDIR/system $bakloc
   rm -f $bakloc/system/bin/ccbins
   echo -e "Current config backed up!\n"
+  sleep 2
 }
 
 restore_config() {
-  local newloc=/data/adb/modules_update/$MODID
-  touch $MODDIR/update
+  local newloc=/data/adb/modules_update/$ID
   rm -rf $newloc
-  mkdir /data/adb/modules_update 2>/dev/null
+  mkdir -p /data/adb/modules_update/$ID 2>/dev/null
   cp -pf $MODDIR/* $newloc 2>/dev/null
   cp -af $bakloc/* $newloc 2>/dev/null
   cp -pf $bakloc/.* $newloc 2>/dev/null
   cp -pf $MODDIR/system/bin/ccbins $newloc/system/bin/ccbins
+  touch $MODDIR/update
   echo -e "Old config restored!\nReboot to apply it!\n"
+  sleep 2
 }
 
-scriptver=3
-branch=master
+hidden_menu() {
+  clear
+  echo "$div"
+  title_div "Welcome to the dark side"
+  echo "$div"
+  $online || { echo -e "Internet is needed for this, going back to main menu\n"; return 0; }
+  title_div "Current branch:"
+  title_div "$branch"
+  echo "$div"
+  title_div "Choose option:"
+  echo "$div"
+  while true; do
+    echo "0: Go back to main menu"
+    echo "1: Force update"
+    echo "2: Switch branch"
+    while true; do
+      read -r choice?'--> '
+      echo " "
+      case $choice in
+        0|1|2) break;;
+        q) quit;;
+        *) echo "Invalid option! Try again";;
+      esac
+    done
+    case $choice in
+      0) break;;
+      1) echo "Applying mod updates and restarting"
+         echo "$scriptver" > $MODDIR/.updated
+         wget -qO $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/changelog.txt 2>/dev/null
+         wget -qO $MODDIR/system/bin/ccbins https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins 2>/dev/null
+         wget -qO $MODDIR/mod-util.sh https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/mod-util.sh 2>/dev/null
+         umount -l /system/bin/ccbins
+         mount -o bind $MODDIR/system/bin/ccbins /system/bin/ccbins
+         ccbins && quit;;
+      2) echo "Enter branch (0 will still return to main menu):"
+         while true; do
+           read -r choice?'--> '
+           echo " "
+           case $choice in
+             0) break 2;;
+             "q") quit;;
+           esac
+           wget --spider https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$choice/ccbins 2>/dev/null || { echo "Branch doesn't exist! Try again"; continue; }
+           branch=$choice
+           sed -i "s/^branch=.*/branch=$branch/" $MODDIR/system/bin/ccbins
+           echo "Switched branch to $branch"
+           break
+         done;;
+    esac
+  done
+  clear
+}
+
+scriptver=4
+branch=testing
 dir=`pwd`; bakloc=/data/local/ccbinsbackup
 locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
 [ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
 rm -f $MODDIR/tmp
 mod_head
 echo " "
+if [ -f $MODDIR/.updated ]; then
+  echo "CCBins succesfully updated!"
+  local oldver="$(cat $MODDIR/.updated)" newver="$scriptver"
+  local oldline=$(sed -n "/^$oldver/=" $MODDIR/.changelog) newline=$(sed -n "/^$newver/=" $MODDIR/.changelog)
+  echo "Changelog: $(sed -n "/^$newver/p" $MODDIR/.changelog)"
+  sed -n "$newline,$oldline p" $MODDIR/.changelog | sed -E '/^[0-9]|^$/d'
+  echo " "
+  sleep 2
+fi
 if test_connection; then
   online=true
   echo -e "\nFetching available binaries"
@@ -322,9 +427,9 @@ if test_connection; then
   wget -qO $MODDIR/.binaries https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/includes.txt 2>/dev/null & e_spinner
   echo " - Done"
   check_updates & e_spinner
-  [ -f $MODDIR/tmp ] && { echo -e " - Applying mod updates and restarting"; ccbins && quit; } || echo " - Ccbins is up to date"
+  [ -f $MODDIR/.updated ] && { echo -e " - Applying mod updates and restarting"; ccbins && quit; } || echo " - Ccbins is up to date"
   check_bin_updates & e_spinner
-  [ -s $MODDIR/tmp ] && { echo -e " - The following binaries need updated:\n"; cat $MODDIR/tmp; } || echo " - Binaries are up to date"
+  [ -f $MODDIR/tmp ] && echo -e " - Done\n" || echo -e " - Binaries are up to date\n"
 else
   online=false
   echo -e "No internet connection!\nOnline functionality disabled"
@@ -342,36 +447,38 @@ while true; do
   echo "$div"
   title_div "Choose option"
   echo "$div"
-  echo "0: Change install location"
-  echo "1: List all installed binaries"
-  echo "2: List all downloadable binaries"
-  echo "3: Remove binary"
-  $online && echo "4: Install binary"
-  [ -s $MODDIR/.installed ] && echo "5: Backup current config"
-  [ -d $bakloc ] && echo -e "6: Restore last config\n7: Erase backup config"
+  echo "0: Refresh CCbins (remove everything - start fresh)"
+  echo "1: Change install location"
+  echo "2: List all installed binaries"
+  echo "3: List all downloadable binaries"
+  echo "4: Remove binary"
+  $online && echo "5: Install binary"
+  [ -s $MODDIR/.installed ] && echo "6: Backup current config"
+  [ -d $bakloc ] && echo -e "7: Restore last config\n8: Erase backup config"
   echo "Type 'q' at any time to quit"
   while true; do
     read -r choice?'--> '
     echo " "
     case $choice in
-      0|1|2|3) break;;
-      4) $online && break || echo "Invalid option! Try again";;
-      5) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
-      6|7) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
+      0|1|2|3|4|99) break;;
+      5) $online && break || echo "Invalid option! Try again";;
+      6) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
+      7|8) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
       q) quit;;
       *) echo "Invalid option! Try again";;
     esac
   done
 
   case $choice in
-    0) change_loc;;
-    1) [ -s $MODDIR/.installed ] && list_installed || echo "No binaries installed!"; print_pause " ";;
-    2) cat $MODDIR/.binaries | awk '{print $1 " " $2}'; echo " ";;
-    3) [ -s $MODDIR/.installed ] && remove_binary || print_pause "No binaries installed!\n";;
-    4) install_binary;;
-    5) backup_config;;
-    6) restore_config;;
-    7) rm -rf $bakloc; print_pause "Backup config erased\n";;
+    0) reset_mod;;
+    1) change_loc;;
+    2) [ -s $MODDIR/.installed ] && list_installed || print_pause "No binaries installed!";;
+    3) cat $MODDIR/.binaries | awk '{print $1 " " $2}'; echo " ";;
+    4) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
+    5) install_binary_menu;;
+    6) backup_config;;
+    7) restore_config;;
+    8) rm -rf $bakloc; print_pause "Backup config erased\n";;
+    99) hidden_menu;;
   esac
-  clear
 done
