v21, remove aria2/tcpdump dynamic, fix tcpdump static

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -42,12 +42,43 @@ set -x 2>$VERLOG
 # > You can start your MOD here.
 # > You can add functions, variables & etc.
 # > Rather than editing the default vars above.
-scriptver=20
+quit() {
+  rm -f $MODDIR/tmp $MODDIR/dlerror
+  kill -10 $proc
+  exit 0
+}
+
+scriptver=21
 branch=master
-# Curl uses boringssl - first appeared in Marshmallow - don't try using ssl in older android versions
+# Doh workaround for dns poisoning
 [ -f $MODDIR/doh ] && { flag=" --doh-url $(tail -n1 $MODDIR/doh)"; doh="$(head -n1 $MODDIR/doh)"; }
+# Curl uses boringssl - first appeared in Marshmallow - don't try using ssl in older android versions
 [ $API -lt 23 ] && alias curl="$MODDIR/curl -kLs$flag" || alias curl="$MODDIR/curl -Ls$flag"
 unset flag
+# Make sure binaries are present
+for i in curl wg wg-quick; do
+  [ -f "$MODDIR/$i" ] && continue
+  [ "$i" == "curl" ] && { echo -e "Curl missing!\nReinstall ccbins or copy curl to root of ccbins module folder!"; quit; }
+  (curl -o $MODDIR/$i https://github.com/Magisk-Modules-Repo/ccbins/master/$i-$ARCH32 & e_spinner "Downloading $i") && echo " - OK" || { echo " - Error"; quit; }
+  set_perm $MODDIR/$i 0 0 755
+done
+# DNS resolution fix for wireguard tunnels - use wireguard dns servers if specified
+if [ "$(pm list packages com.wireguard.android)" ] && [ "$(wg show)" ]; then
+  curlalias="$(alias | grep 'curl=' | sed -r "s/curl='(.*)'/\1/")"
+  wgint="$(wg show | grep 'interface' | sed 's/interface: //')"
+  # Initial log/output from starting a tunnel is only surefire way to get the dns addresses to my knowledge
+  for i in $wgint; do
+    wg-quick down $i >/dev/null; wg-quick up $i | tee $MODDIR/tmp >/dev/null
+    j="$(grep setResolverConfiguration $MODDIR/tmp | awk -F '[()]' '{print $2}' | cut -d '[' -f2 | cut -d ']' -f1 | sed 's/ //g')"
+    [ "$j" ] && dnsrvs="$dnsrvs,$j"
+    j="$(grep setResolverConfiguration $MODDIR/tmp | awk -F '[()]' '{print $2}' | cut -d '[' -f3 | cut -d ']' -f1 | sed 's/ //g')"
+    [ "$j" ] && dnsrvs="$dnsrvs,$j"
+  done
+  dnsrvs="$(echo "$dnsrvs" | sed 's/^,//')"
+  rm -f $MODDIR/tmp
+  alias curl="$(echo "$curlalias" | sed "s/curl /curl --dns-servers $dnsrvs /")"
+  unset curlalias wgint
+fi
 dir=`pwd`; bakloc=/data/local/ccbinsbackup
 locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
 [ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
@@ -63,12 +94,6 @@ test_connection() {
     fi
   done & e_spinner "Testing internet connection"
   ) && echo " - OK" || { echo " - Error"; false; }
-}
-
-quit() {
-  rm -f $MODDIR/tmp $MODDIR/dlerror
-  kill -10 $proc
-  exit 0
 }
 
 print_pause() {
