v15

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -39,6 +39,15 @@ set -x 2>$VERLOG
 # > You can start your MOD here.
 # > You can add functions, variables & etc.
 # > Rather than editing the default vars above.
+scriptver=15
+branch=master
+API=`getprop ro.build.version.sdk`
+# Curl uses boringssl - first appeared in Marshmallow - don't try using ssl in older android versions
+[ $API -lt 23 ] && alias curl="$MODDIR/curl -kL" || alias curl="$MODDIR/curl -L"
+dir=`pwd`; bakloc=/data/local/ccbinsbackup
+locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
+[ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
+
 quit() {
   rm -f $MODDIR/tmp
   exit 0
@@ -64,20 +73,20 @@ reset_mod() {
 check_updates() {
   echo -e "\nChecking for mod updates"
   rm -f $MODDIR/.updated $MODDIR/.updatedfiles
-  wget -qO $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/changelog.txt 2>/dev/null
+  curl -so $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/changelog.txt 2>/dev/null
   for i in mod-util.sh,MODUTILVCODE system/bin/ccbins,scriptver service.sh,filever; do
     local file="$(echo $i | cut -d , -f1)" value="$(echo $i | cut -d , -f2)"
-    if [ `wget -qO - https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/$(basename $file) 2>/dev/null | grep "^$value=" | cut -d = -f2` -gt `grep "^$value=" $MODDIR/$file | cut -d = -f2` ]; then
+    if [ `curl -so - https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/$(basename $file) 2>/dev/null | grep "^$value=" | cut -d = -f2` -gt `grep "^$value=" $MODDIR/$file | cut -d = -f2` ]; then
       echo "$scriptver" > $MODDIR/.updated
       echo "$(basename $file)" >> $MODDIR/.updatedfiles
-      wget -qO $MODDIR/$file https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/$(basename $file) 2>/dev/null
+      curl -so $MODDIR/$file https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/$(basename $file) 2>/dev/null
       [ "$file" == "system/bin/ccbins" ] && { umount -l /$file; mount -o bind $MODDIR/$file /$file; }
     fi
   done
 }
 
 find_conflicts() {
-  echo "Checking for conflicting modules"
+  echo -e "\nChecking for conflicting modules"
   rm -f $MODDIR/tmp
   [ -s $MODDIR/.installed ] || return 0
   local locs="$(awk '{print $3}' $MODDIR/.installed | xargs -n1 | sort -u)" binaries="$(awk '{print $1}' $MODDIR/.installed | xargs -n1 | sort -u)"
@@ -122,6 +131,41 @@ info() {
   echo "You'll want to install binaries to the lowest priority location unless you want to overwrite any existing ones"
   echo "Running 'echo \$PATH' will show you the priority with highest being first"
   echo "Vendor is typically lowest and product is typically highest (if present)"
+}
+
+binary_update_menu() {
+  clear
+  while true; do
+    echo "$div"
+    title_div "Binary Update Menu"
+    echo "$div"
+    echo "0: Go back to main menu"
+    if $autoupdate; then
+      echo "1: Disable automatic binary updates at launch"
+    else
+      echo "1: Enable automatic binary updates at launch (recommended)"
+      $online && echo "2: Check for binary updates"
+    fi
+    while true; do
+      read -r choice?'--> '
+      echo " "
+      case $choice in
+        0|1|2) break;;
+        q) quit;;
+        *) echo "Invalid option! Try again";;
+      esac
+    done
+    case $choice in
+      0) break;;
+      1) $autoupdate && { touch $MODDIR/.disable_autoupdate; autoupdate=false; } || { rm -f $MODDIR/.disable_autoupdate; autoupdate=true; };;
+      2) if $autoupdate || ! $online; then
+           echo "Invalid option! Try again"
+         else
+           check_bin_updates & e_spinner
+           [ -f $MODDIR/tmp ] && echo -e " - Done\n" || echo -e " - Binaries are up to date\n"
+         fi;;
+    esac
+  done
 }
 
 list_locs() {
@@ -189,13 +233,13 @@ install_binary() {
   [ "$file" == "$MODDIR/.binaries" ] && local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary" || local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/dynamic"
   for i in $(grep -w $binary $file | awk '{print $3}' | sed "s/,/ /g"); do
     check_conflicts
-    $spin && { wget -O $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null & e_spinner; } || wget -O $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null
+    $spin && { curl -so $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null & e_spinner; } || curl -so $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null
     set_perm $MODDIR$insloc/$i 0 2000 0755
   done
   if [ "$extras" ] && [ ! -f $MODDIR/.$ibinary ]; then
     for i in $(echo $extras | sed "s|,| |g"); do
       if wget -q --spider $url/$i.zip 2>/dev/null; then
-        $spin && { wget -qO $MODDIR/$i.zip $url/$i.zip 2>/dev/null & e_spinner; } || wget -qO $MODDIR/$i.zip $url/$i.zip 2>/dev/null
+        $spin && { curl -so $MODDIR/$i.zip $url/$i.zip 2>/dev/null & e_spinner; } || curl -so $MODDIR/$i.zip $url/$i.zip 2>/dev/null
         unzip -l $MODDIR/$i.zip | awk '{print $4}' | sed -e '/^$/d' -e '/^Name$/d' -e '/^----$/d' -e '/\/$/d' >> $MODDIR/.$ibinary
         unzip -qod $MODDIR/system $MODDIR/$i.zip
         rm -f $MODDIR/$i.zip
@@ -208,7 +252,7 @@ install_binary() {
     done
   fi
   if wget -q --spider $url/install.sh 2>/dev/null; then
-    $spin && { wget -qO $MODDIR/install.sh $url/install.sh 2>/dev/null & e_spinner; } || wget -qO $MODDIR/install.sh $url/install.sh 2>/dev/null
+    $spin && { curl -so $MODDIR/install.sh $url/install.sh 2>/dev/null & e_spinner; } || curl -so $MODDIR/install.sh $url/install.sh 2>/dev/null
     . $MODDIR/install.sh
     rm -f $MODDIR/install.sh
   fi
@@ -218,7 +262,7 @@ install_ncursesw() {
   [ "$1" == "-u" ] && local update=true || local update=false
   $update && echo " - Updating NCursesw (`cat $MODDIR/.ncursesver` -> `cat $MODDIR/tmp`)" || echo " - Installing NCursesw v`cat $MODDIR/tmp`"
   mv -f $MODDIR/tmp $MODDIR/.ncursesver
-  wget -O $MODDIR/system/ncursesw.zip https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/ncursesw/ncursesw-$ARCH.zip 2>/dev/null
+  curl -so $MODDIR/system/ncursesw.zip https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/ncursesw/ncursesw-$ARCH.zip 2>/dev/null
   unzip -qod $MODDIR/system $MODDIR/system/ncursesw.zip
   rm -f $MODDIR/system/ncursesw.zip
   $update && echo " - NCursesw has been updated!" || echo " - NCursesw has been installed!"
@@ -226,7 +270,7 @@ install_ncursesw() {
 
 check_bin_updates() {
   echo -e "\nChecking for binary updates"
-  wget -qO $MODDIR/tmp https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/ncursesw/version.txt 2>/dev/null
+  curl -so $MODDIR/tmp https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/ncursesw/version.txt 2>/dev/null
   if [ ! -f $MODDIR/.ncursesver ]; then
     install_ncursesw 
   else
@@ -244,7 +288,7 @@ check_bin_updates() {
   while read -r line; do
     [ "$(echo "$line" | awk '{print $4}')" == "dynamic" ] && local file=$MODDIR/.binaries-dynamic || local file=$MODDIR/.binaries
     local binloc="$(echo "$line" | awk '{print $3}')" binary="$(echo "$line" | awk '{print $1}')" insver="$(echo "$line" | awk '{print substr($2, 3, length($2) - 3)}')"
-    local insloc="$binloc" newver="$(grep -w $binary $MODDIR/.binaries | awk '{print substr($2, 3, length($2) - 3)}')" ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]') extras="$(grep -w $binary $MODDIR/.binaries | awk '{print $4}')"
+    local insloc="$binloc" newver="$(grep -w $binary $file | awk '{print substr($2, 3, length($2) - 3)}')" ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]') extras="$(grep -w $binary $file | awk '{print $4}')"
     [ "$insver" == "/a" ] && insver="0.0"
     # Add 0 before final number if single digit or compare won't work
     for i in insver newver; do
@@ -371,16 +415,16 @@ restore_config() {
 
 force_update() {
   echo "$scriptver" > $MODDIR/.updated
-  wget -qO $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/changelog.txt 2>/dev/null
-  wget -qO $MODDIR/system/bin/ccbins https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/ccbins 2>/dev/null
-  wget -qO $MODDIR/mod-util.sh https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/mod-util.sh 2>/dev/null
+  curl -so $MODDIR/.changelog https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/changelog.txt 2>/dev/null
+  curl -so $MODDIR/system/bin/ccbins https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/ccbins 2>/dev/null
+  curl -so $MODDIR/mod-util.sh https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/mod-util.sh 2>/dev/null
   umount -l /system/bin/ccbins
   mount -o bind $MODDIR/system/bin/ccbins /system/bin/ccbins
   ccbins && quit
 }
 
 hidden_menu() {
-  wget -qO - https://api.github.com/repos/Zackptg5/Cross-Compiled-Binaries-Android/branches 2>/dev/null | grep "name" | awk '{print FNR ": " substr($2, 2, length($2) -3)}' > $MODDIR/tmp
+  curl -so - https://api.github.com/repos/Zackptg5/Cross-Compiled-Binaries-Android/branches 2>/dev/null | grep "name" | awk '{print FNR ": " substr($2, 2, length($2) -3)}' > $MODDIR/tmp
   sed -i "1i0: Keep current branch, go back to main menu" $MODDIR/tmp
   while true; do
     clear
@@ -407,7 +451,7 @@ hidden_menu() {
     done
     case $choice in
       0) break;;
-      1) echo "Applying mod updates and restarting"
+      1) echo "Applying mod updates and restarting ccbins"
          force_update
          ;;
       2) echo "Which branch?"
@@ -430,17 +474,10 @@ hidden_menu() {
   clear
 }
 
-API=`getprop ro.build.version.sdk`
-find $MODDIR/system -type l -delete
-sed -i '/find $MODDIR\/system -type l -delete/,+1 d' $MODDIR/system/bin/ccbins
-scriptver=14
-branch=master
-dir=`pwd`; bakloc=/data/local/ccbinsbackup
-locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
-[ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
 rm -f $MODDIR/tmp
 mod_head
 echo " "
+[ -f $MODDIR/.disable_autoupdate ] && autoupdate=false || autoupdate=true
 if [ -f $MODDIR/.updated ]; then
   echo "CCBins succesfully updated!"
   local oldver="$(cat $MODDIR/.updated)" newver="$scriptver"
@@ -457,13 +494,15 @@ if test_connection; then
   online=true
   echo -e "\nFetching available binaries"
   rm -f $MODDIR/.binaries $MODDIR/.binaries-dynamic
-  wget -qO $MODDIR/.binaries https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes.txt 2>/dev/null & e_spinner
-  wget -qO $MODDIR/.binaries-dynamic https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes-dynamic.txt 2>/dev/null & e_spinner
+  curl -so $MODDIR/.binaries https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes.txt 2>/dev/null & e_spinner
+  curl -so $MODDIR/.binaries-dynamic https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes-dynamic.txt 2>/dev/null & e_spinner
   echo " - Done"
   check_updates & e_spinner
-  [ -f $MODDIR/.updated ] && { echo -e " - Applying mod updates and restarting"; ccbins && quit; } || echo " - Ccbins is up to date"
-  check_bin_updates & e_spinner
-  [ -f $MODDIR/tmp ] && echo -e " - Done\n" || echo -e " - Binaries are up to date\n"
+  [ -f $MODDIR/.updated ] && { echo -e " - Applying mod updates and restarting ccbins"; ccbins && quit; } || echo " - Ccbins is up to date"
+  if $autoupdate; then
+    check_bin_updates & e_spinner
+    [ -f $MODDIR/tmp ] && echo " - Done" || echo " - Binaries are up to date"
+  fi
 else
   online=false
   echo -e "No internet connection!\nOnline functionality disabled"
@@ -479,27 +518,32 @@ while true; do
   echo "Current install location:"
   echo "$insloc"
   echo "$div"
+  echo "Auto-update binaries at launch:"
+  $autoupdate && echo "Enabled (recommended)" || echo "Disabled"
+  echo "$div"
+  [ "$branch" == "master" ] || echo -e "Current branch:\n$branch\n$div"
   title_div "Choose option"
   echo "$div"
   echo "0: Refresh CCbins (remove everything - start fresh)"
   echo "1: General Information"
   echo "2: Change install location"
-  echo "3: List all installed binaries"
-  echo "4: List all downloadable binaries"
-  echo "5: Remove binary"
-  $online && echo "6: Install binary"
-  $online && [ $API -ge 21 ] && echo "7: Install dynamic linked binary"
-  [ -s $MODDIR/.installed ] && echo "8: Backup current config"
-  [ -d $bakloc ] && echo -e "9: Restore last config\n10: Erase backup config"
+  echo "3: Binary Update Settings"
+  echo "4: List all installed binaries"
+  echo "5: List all downloadable binaries"
+  echo "6: Remove binary"
+  $online && echo "7: Install binary"
+  $online && [ $API -ge 21 ] && echo "8: Install dynamic linked binary"
+  [ -s $MODDIR/.installed ] && echo "9: Backup current config"
+  [ -d $bakloc ] && echo -e "10: Restore last config\n11: Erase backup config"
   echo "Type 'q' at any time to quit"
   while true; do
     read -r choice?'--> '
     echo " "
     case $choice in
-      0|1|2|3|4|5|99) break;;
-      6|7) $online && break || echo "Invalid option! Try again";;
-      8) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
-      9|10) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
+      0|1|2|3|4|5|6|99) break;;
+      7|8) $online && break || echo "Invalid option! Try again";;
+      9) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
+      10|11) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
       q) quit;;
       *) echo "Invalid option! Try again";;
     esac
@@ -509,14 +553,15 @@ while true; do
     0) reset_mod;;
     1) info;;
     2) change_loc;;
-    3) [ -s $MODDIR/.installed ] && list_installed || print_pause "No binaries installed!";;
-    4) cat $MODDIR/.binaries | awk '{print $1 " " $2}'; echo " ";;
-    5) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
-    6) install_binary_menu;;
-    7) install_binary_menu -d;;
-    8) backup_config;;
-    9) restore_config;;
-    10) rm -rf $bakloc; print_pause "Backup config erased\n";;
+    3) binary_update_menu;;
+    4) [ -s $MODDIR/.installed ] && list_installed || print_pause "No binaries installed!";;
+    5) cat $MODDIR/.binaries | awk '{print $1 " " $2}'; echo " ";;
+    6) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
+    7) install_binary_menu;;
+    8) install_binary_menu -d;;
+    9) backup_config;;
+    10) restore_config;;
+    11) rm -rf $bakloc; print_pause "Backup config erased\n";;
     99) hidden_menu;;
   esac
 done
